export function CodingAgentDocumentation(){
  return <>
    <p>Run Claude Code, Codex, GitHub Copilot CLI, OpenCode or Pi inside the self-hosted Studio editor. The provider/session pattern is informed by Paseo without depending on its server. BYOK generation and external MCP access remain separate.</p>
    <h2>Enable on your Node server</h2>
    <ol className="docs-numbered"><li>Install and authenticate trusted, pinned native CLIs under the dedicated OS account that runs Studio.</li><li>Read the intended Studio account's exact user ID from authenticated <code>GET /api/auth/me</code>.</li><li>Set <code>STUDIO_AGENTS_ENABLED=true</code> and <code>STUDIO_AGENT_OWNER_ID</code> to that one ID, then restart. Node 24+ is required; Cloudflare cannot run local CLIs.</li><li>Check Settings → Agent access. Detected installation and model catalog membership do not prove authentication or entitlement. Omit a model override for the CLI default; OpenCode uses <code>provider/model</code>.</li></ol>
    <p>Default binaries are claude, codex, copilot, opencode and pi. Executable paths can be overridden with <code>STUDIO_AGENT_CLAUDE_BIN</code>, <code>STUDIO_AGENT_CODEX_BIN</code>, <code>STUDIO_AGENT_COPILOT_BIN</code>, <code>STUDIO_AGENT_OPENCODE_BIN</code> and <code>STUDIO_AGENT_PI_BIN</code>. Native protocol compatibility must be verified for installed versions.</p>
    <h2>Docker login persistence</h2>
    <p>Set <code>CODING_AGENT_PACKAGES</code> to space-separated, operator-pinned npm CLI packages before building. Empty by default; never put credentials in build arguments. Compose persists CLI login/configuration in <code>studio-agent-home:/home/node</code> and Studio data/draft workspaces in <code>studio-data:/data</code>. Back up both privately; do not mount personal homes or Git workspaces.</p>
    <pre><code>{'docker compose up --build -d\n# Authenticate an installed CLI as the container node user:\ndocker compose exec studio codex login --device-auth'}</code></pre>
    <h2>Design, preview, apply</h2>
    <p>Save canvas edits and approve any existing brief. Choose Coding agent in chat, or Design with agent in the first-design brief. Sessions persist, with one turn/proposal action per project. Text, tool activity, permission/input requests, errors and provider-reported usage appear in the log. Unknown usage is not zero. Stop agent terminates the owned process and retains draft edits. Restart marks unfinished turns interrupted; it never silently reruns paid work.</p>
    <p>Preview proposal on canvas, inspect its pages, then Apply proposal or Discard. Tools cannot save, approve, publish, export or change Git. Apply checks the reviewed draft version, document revision, approved brief revision and owned assets using the shared save service. Exact Apply retries return the same receipt. Conflicts require reconciliation or discard, not higher revisions to overwrite newer work.</p>
    <h2>API and agent clients</h2>
    <p>Discover <code>codingAgents</code> in <code>/api/schema</code>, endpoints in <code>/api/openapi</code>, or <code>dsa agents schema</code>. Network MCP exposes <code>agent_*</code>; browser WebMCP uses one compact <code>studio_agents</code> tool with operation (agent_* name), parameters (id, sessionId, provider), canonical body and optional after. Host execution requires the designated owner's API key or browser session, not ordinary OAuth <code>studio</code> scope.</p>
    <pre><code>{'dsa agents providers\ndsa agents create PROJECT_ID --provider codex --revision OBSERVED_REVISION\ndsa agents send PROJECT_ID SESSION_ID --file turn.json\ndsa agents events PROJECT_ID SESSION_ID --after LAST_SEQUENCE\ndsa agents proposal PROJECT_ID SESSION_ID\n# Only after human review:\ndsa agents apply PROJECT_ID SESSION_ID --proposal-version REVIEWED_DRAFT_VERSION'}</code></pre>
    <p>Send JSON contains a stable UUID requestId, prompt and expectedRevision. Keep the exact body for uncertain retries. Polling returns up to 200 events; continue after the last seq. HTTP <code>stream=true</code> enables SSE; <code>Last-Event-ID</code> overrides after on reconnect. CLI events are JSON polling. Use command help for list, get, stop, respond and discard.</p>
    <h2>Security and verification limits</h2>
    <p>Turns use private workspaces and an authenticated, turn-scoped loopback gateway exposing only Studio draft tools. Tools recheck authorization and validate schemas/assets. Child environments exclude Studio account keys, encryption keys and OAuth app secrets; provider credentials stay with the native CLI.</p>
    <p>Claude uses its Agent SDK, Codex app-server, Copilot ACP, OpenCode local HTTP/SSE and Pi RPC with a Studio extension. Built-in shell/writes are disabled or denied where supported, but this is not an OS sandbox or isolation from arbitrary plugins/global configuration. Use dedicated service accounts/containers and limit access to the trusted designated account.</p>
    <p>Missing CLIs, authentication failures, model denials and protocol errors are explicit; production never substitutes fixtures. Local contract tests do not prove live generation from all five providers. Live smoke tests require credentials and consent to possible charges.</p>
  </>;
}
