export function CodingAgentDocumentation(){
  return <>
    <p>Run Claude Code, Codex, GitHub Copilot CLI, OpenCode or Pi inside the self-hosted Studio editor. The provider/session pattern is informed by Paseo without depending on its server. BYOK generation and external MCP access remain separate.</p>
    <h2>Enable on your Node server</h2>
    <ol className="docs-numbered"><li>Install and authenticate trusted, pinned native CLIs under the dedicated OS account that runs Studio.</li><li>Read the intended Studio account's exact user ID from authenticated <code>GET /api/auth/me</code>.</li><li>Set <code>STUDIO_AGENTS_ENABLED=true</code> and <code>STUDIO_AGENT_OWNER_ID</code> to that one ID, then restart. Node 24+ is required; Cloudflare cannot run local CLIs.</li><li>Check Settings → Agent access. Detected installation and model catalog membership do not prove authentication or entitlement. Omit a model override for the CLI default; OpenCode uses <code>provider/model</code>.</li></ol>
    <p>Default binaries are claude, codex, copilot, opencode and pi. Executable paths can be overridden with <code>STUDIO_AGENT_CLAUDE_BIN</code>, <code>STUDIO_AGENT_CODEX_BIN</code>, <code>STUDIO_AGENT_COPILOT_BIN</code>, <code>STUDIO_AGENT_OPENCODE_BIN</code> and <code>STUDIO_AGENT_PI_BIN</code>. Native protocol compatibility must be verified for installed versions.</p>
    <h2>Docker login persistence</h2>
    <p>Set <code>CODING_AGENT_PACKAGES</code> to space-separated, operator-pinned npm CLI packages before building. Empty by default; never put credentials in build arguments. Compose persists CLI login/configuration in <code>studio-agent-home:/home/node</code> and Studio data/draft workspaces in <code>studio-data:/data</code>. Back up both privately; do not mount personal homes or Git workspaces.</p>
    <pre><code>{'docker compose up --build -d\n# Authenticate an installed CLI as the container node user:\ndocker compose exec studio codex login --device-auth'}</code></pre>
    <h2>Design, preview, apply</h2>
    <p>Projects open in Chat beside a preview on desktop, or Chat / Preview tabs on smaller screens. Choose an API connection or native agent in the same AI picker; the choice is remembered for this account on this browser. Options contains model overrides; History contains advanced session selection. Sessions start or resume automatically when you send a request.</p>
    <p>For a new idea, answer one question at a time, review the editable scope card, then choose Approve and create. Native interview sessions can only read the brief and submit questions/scope. After approval, a separate design session continues in the same workspace. Edit opens manual tools without losing your unsent message; Save and send saves pending manual edits before generation.</p>
    <p>Drafts preview automatically. Choose View design on mobile, inspect the pages, then Apply proposal or Discard. Tools cannot save, approve, publish, export or change Git. Apply checks the reviewed draft version, document revision, approved brief revision and owned assets using the shared save service. Exact Apply retries return the same receipt. Conflicts require reconciliation or discard, not higher revisions to overwrite newer work.</p>
    <p>One turn/proposal action runs per project. Activity details holds tool activity and reported usage; unknown usage is not zero. Permission requests and errors stay visible. Stop agent retains draft edits. Reload restores the saved conversation without starting a paid turn; a server restart marks unfinished turns interrupted.</p>
    <h2>API and agent clients</h2>
    <p>Before sending a prompt, Claude sessions wait up to 30 seconds for the Studio MCP connection and every required tool. Missing tools or a failed connection stop the turn with <code>agent_tools_unavailable</code> in Chat and the event feed; the prompt is not sent and saved brief/design state is unchanged. Check the pinned Claude CLI and MCP setup on the server, then explicitly retry. Reload and an exact request-ID retry never restart the failed turn. Stop remains available while connecting.</p>
    <p>Discover <code>codingAgents</code> in <code>/api/schema</code>, endpoints in <code>/api/openapi</code>, or <code>dsa agents schema</code>. Network MCP exposes <code>agent_*</code>; browser WebMCP uses one compact <code>studio_agents</code> tool with operation (agent_* name), parameters (id, sessionId, provider), canonical body and optional after. Host execution requires the designated owner's API key or browser session, not ordinary OAuth <code>studio</code> scope.</p>
    <pre><code>{'dsa agents providers\ndsa agents create PROJECT_ID --provider codex --revision OBSERVED_REVISION\ndsa agents send PROJECT_ID SESSION_ID --file turn.json\ndsa agents events PROJECT_ID SESSION_ID --after LAST_SEQUENCE\ndsa agents proposal PROJECT_ID SESSION_ID\n# Only after human review:\ndsa agents apply PROJECT_ID SESSION_ID --proposal-version REVIEWED_DRAFT_VERSION'}</code></pre>
    <p>Send JSON contains a stable UUID requestId, prompt and expectedRevision. Keep the exact body for uncertain retries. Polling returns up to 200 events; continue after the last seq. HTTP <code>stream=true</code> enables SSE; <code>Last-Event-ID</code> overrides after on reconnect. CLI events are JSON polling. Use command help for list, get, stop, respond and discard.</p>
    <p>Before approval, create with <code>purpose: interview</code> and the observed <code>expectedBriefRevision</code>; include that brief revision in each message too. CLI creation uses <code>--purpose interview --brief-revision N</code>. After approval, create a separate design session (the default purpose). The server rejects design tools and Apply/Discard in interview sessions.</p>
    <p>Read committed brief snapshots with <code>GET /api/projects/ID/brief/history?after=N</code>, MCP <code>get_design_brief_history</code>, WebMCP <code>studio_get_brief_history</code>, or <code>dsa brief history ID --after N</code>. Continue with <code>nextAfter</code> until null. Existing projects start history at their migration snapshot, not reconstructed past revisions.</p>
    <h2>Security and verification limits</h2>
    <p>Turns use private workspaces and an authenticated, turn-scoped loopback gateway exposing only Studio tools for the session purpose. Interview sessions expose only studio_brief_context and studio_submit_interview. Tools recheck authorization and validate schemas/assets. Child environments exclude Studio account keys, encryption keys and OAuth app secrets; provider credentials stay with the native CLI.</p>
    <p>Claude uses its Agent SDK, Codex app-server, Copilot ACP, OpenCode local HTTP/SSE and Pi RPC with a Studio extension. Built-in shell/writes are disabled or denied where supported, but this is not an OS sandbox or isolation from arbitrary plugins/global configuration. Use dedicated service accounts/containers and limit access to the trusted designated account.</p>
    <p>Missing CLIs, authentication failures, model denials and protocol errors are explicit; production never substitutes fixtures. Local contract tests do not prove live generation from all five providers. Live smoke tests require credentials and consent to possible charges.</p>
  </>;
}
